### ISSUE TITLE
[Bug] Error on guild remove

### ISSUE THREAD

**Issue by monk-afk** [monk-afk/moe#5]
```
2024-07-14 19:32:55 ERROR    discord.client Ignoring exception in on_guild_remove
Traceback (most recent call last):
  File "/.../discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/.../moe/cogs/events.py", line 27, in on_guild_remove
    await drop_guild_input_ids(guild_id)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by monk-afk** [comment]
fixed in 0.0.5
